### ISSUE TITLE
No cross-schema way to get digests

### ISSUE THREAD

**Issue by AstraLuma** [crashvb/docker-registry-client-async#12]
There is no abstraction around manifests to get digests (in particular, config)

**Comment by crashvb** [comment]
This was split out of another [project](https://github.com/crashvb/docker-sign-verify/blob/master/docker_sign_verify/registryv2manifest.py#L93) that has a more generalized usage than just v2 registries. You should be able to borrow from that code base and sub-class Manifest to get the abstraction your looking for here.

Will look into backporting the methods to this code base as part of a long term solution.
