### ISSUE TITLE
Retrying

### ISSUE THREAD

**Issue by AstraLuma** [crashvb/docker-registry-client-async#13]
Add an option for retrying?

**Comment by crashvb** [comment]
Looking into [inyutin/aiohttp_retry](/inyutin/aiohttp_retry), but it doesn't seem to be a drop in alternative.

[feature/issue_13](/crashvb/docker-registry-client-async/tree/feature/issue_13), if you want to give it a try ...

**Comment by crashvb** [comment]
The fix for issue #25 adds support for overriding the aiohttp ClientSession; it should not be possible to use [inyutin/aiohttp_retry](https://github.com/inyutin/aiohttp_retry), or similar.
