### ISSUE TITLE
Typo in the default Accept header

### ISSUE THREAD

**Issue by skrech** [crashvb/docker-registry-client-async#29]
Hello it's me again! :)

I was just struck by a strange behaviour for one registry, returning HTTP 400 Bad Request on getting manifest. I've debugged the issue and it turned out the registry returns distribution manifest v1 and thus a slight typo in the default Accept header was causing the issue. 
The problem is here (missing a comma on the line):
https://github.com/crashvb/docker-registry-client-async/blob/main/docker_registry_client_async/dockerregistryclientasync.py#L79

**Comment by crashvb** [comment]
Hey skrech :)

Good find, typo fixed and released. :+1: 

I wasn't able to reproduce the error when retrieving an [old image](https://hub.docker.com/layers/busybox/library/busybox/1.23.2/images/2824fe048727a69da66cf1be00cebd3bb9cfe1f238473693aa9358b411208527?context=explore) from dockerhub, and I'm not sure I have old enough tooling in place to dynamically build an image with a v1 manifest using a local registry; I'd have to construct the manifest by hand, which is doable, but I'm not sure it's worth it.

That being said, I also included a unit [test](https://github.com/crashvb/docker-registry-client-async/blob/4318bdb5f8ab1c7c852167cf1842cfddb6e42cfc/tests/test_dockerregistryclientasync.py#L2346) to verify that a v1 manifest can be retrieved from dockerhub, but without a negative scenario it's more of a sanity check. If you've got the time and the setup, I'm curious to know if swapping out the image in test_29 with the one that was failing locally results in an error prior to fixing the typo, and likewise, if it passes after the typo is corrected.

Either way, thank you :)
