### ISSUE TITLE
Authentication tokens lifecycle

### ISSUE THREAD

**Issue by skrech** [crashvb/docker-registry-client-async#30]
Hello, 

I've hit the problem of DRCA not refreshing tokens for repositories already interacted with. I find this as major problem, since from how DRCA is structured it's clear that DRCA is best instantiated once for the lifecycle of the application (taking care of connection pooling and credentials management) but with no token refreshing this is pretty much impractical now.

I have the use case where I'm downloading images for various forms of scanning that my backend is doing. To improve performance and scalability I'm checking if an image has already been scanned, so I can skip scanning it again. However, if the user supplies me with `image:tag` I have to resolve that to `image@digest` (by making a request via DRCA to the registry) and if I have indeed scanned that image this would mean I already acquired a token for that repository (scope). So, when I try to resolve a tag to digest a second time and this happens several minutes later, the token will be expired and the request would fail with 401 Unauthorized. 

The same happens even with anonymous access to DockerHub because DockerHub mandates token-based access for anonymous users. 

For the time being, I've made brutal hack to workaround the problem: monkey-patched DRCA with `_get_token=_get_auth_token` which forces getting new token on every request. Apparently, this is very bad for performance (and increases the chances of throttling on the registry side), so it'd be great to have token refresh logic.

**Comment by crashvb** [comment]
Hey skrech,

I [agree](https://github.com/crashvb/docker-registry-client-async/blob/4318bdb5f8ab1c7c852167cf1842cfddb6e42cfc/docker_registry_client_async/dockerregistryclientasync.py#L413) this is an issue. I stopped short originally because I wasn't sure if there was a standard library that could accomplish the task, or if storing / checking the expiry time was going to need to be implemented.

Do you know if there is something that can be dropped in-place?

**Comment by skrech** [comment]
Hey @crashvb, I'm yet to implement OAuth2 auth for the application I'm doing, but I intend to use https://docs.authlib.org
However, it dropped its support for `aiohttp` (in favor of httpx) that DRCA is using. :/
